//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCIsTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isler
    {
        public int isId { get; set; }
        public string isAd { get; set; }
        public string isAciklama { get; set; }
        public Nullable<System.DateTime> isTarih { get; set; }
        public Nullable<int> isPersonelId { get; set; }
        public Nullable<System.DateTime> iletilenTarih { get; set; }
        public Nullable<System.DateTime> yapilanTarih { get; set; }
        public string isDurum { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
