//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCIsTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkiler
    {
        public int yetkiId { get; set; }
        public Nullable<int> personelId { get; set; }
        public Nullable<int> birimId { get; set; }
        public Nullable<int> yetkiTurId { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual YetkiTurler YetkiTurler { get; set; }
    }
}
